# Generated by Django 4.2.4 on 2023-08-09 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_alter_colaboradores_user'),
        ('documentos', '0002_documentos_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.colaboradores'),
            preserve_default=False,
        ),
    ]
