# Generated by Django 4.2.4 on 2023-08-09 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colaboradores', '0002_colaboradores_departamento_colaboradores_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
